### PR TITLE
PHP 8 support and PSR-4 compliance

### PR DESCRIPTION
**Pull request by flemeur**
This PR add support for PHP 8.0 and fixes a PSR-4 warning when installing through composer

### CODE REVIEW

**Comment by flemeur** [comment]
Hi @jahsome 

Not sure if you are seeing this, so I'll try tagging you :)

**Comment by jahsome** [comment]
Hi @flemeur thanks for opening this. I somehow missed notifications but I'll look this over tonight and get it merged.

**Comment by flemeur** [comment]
Hi @jahsome
That's awesome. Looking forward to getting it merged 😊

**Comment by michaelvaes** [comment]
Would be good to get it in the official repo. I've tested and using now @flemeur his branch.

**Comment by schakko** [comment]
Same here, I am using @flemeur's branch without any problems.

**Comment by flemeur** [comment]
@jahsome Any chance of getting this merged soon? :)

**Comment by mohamedpsc** [comment]
@jahsome I hope you can merge and release this one soon

**Comment by jahsome** [comment]
Hi All,

Apologies for neglecting this. I've merged the PR and tagged v1.0.0 (and pushed to packagist). Please let me know if there are any issues.

**Pull request merged**
